# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
        torch-version: [2.6.0]
        cuda-version: ['cpu']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install CUDA ${{ matrix.cuda-version }}
      if: ${{ matrix.cuda-version != 'cpu' }}
      run: |
        bash .github/workflows/cuda/${{ matrix.cuda-version }}-${{ runner.os }}.sh

    - name: Install PyTorch ${{ matrix.torch-version }}+${{ matrix.cuda-version }}
      run: |
        pip install torch==${{ matrix.torch-version }} --extra-index-url https://download.pytorch.org/whl/${{ matrix.cuda-version }}
        python -c "import torch; print('PyTorch:', torch.__version__)"
        python -c "import torch; print('CUDA:', torch.version.cuda)"
    - name: Install torch_scatter
      run: |
        pip install torch-scatter -f https://data.pyg.org/whl/torch-${{ matrix.torch-version }}+${{ matrix.cuda-version }}.html
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt
        pip install -e .; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 graphmodels tests --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 graphmodels tests --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Debug Python Path
      run: python -c "import sys; print(sys.path)"
    - name: Test with pytest
      run: |
        pytest tests/
